### ISSUE TITLE
basic run on Linux Ubuntu 14.04

### ISSUE THREAD

**Issue by ljgww** [bencentra/md2html2pdf#3]
It seems that there is an issue with section of source that covers linux execution.
Patch? 

       $ md2html2pdf
        /usr/lib/node_modules/md2html2pdf/src/converter.js:30
        function log(...messages) {
                     ^^^

        SyntaxError: Unexpected token ...
            at exports.runInThisContext (vm.js:53:16)
            at Module._compile (module.js:373:25)
            at Object.Module._extensions..js (module.js:416:10)
            at Module.load (module.js:343:32)
            at Function.Module._load (module.js:300:12)
            at Module.require (module.js:353:17)
            at require (internal/module.js:12:17)
            at Object.<anonymous> (/usr/lib/node_modules/md2html2pdf/index.js:5:19)
            at Module._compile (module.js:409:26)
            at Object.Module._extensions..js (module.js:416:10)

`$ node -v
v4.8.4`
`$ npm -v
2.15.11`

**Comment by ljgww** [comment]
resolved by installing node 6.11.1
